include:
  - path: akumuli/compose.yaml
  - path: cassandra/compose.yaml
  - path: clickhouse/compose.yaml
  - path: cratedb/compose.yaml
  - path: influx/compose.yaml
  - path: mongo/compose.yaml
  - path: questdb/compose.yaml
  - path: siridb/compose.yaml
  - path: timescaledb/compose.yaml